// api/index.ts — 클라이언트 API 계층 배럴. 규범: docs/BACKEND.md §4·§6.
// 계층 규칙: src/api → src/schema만 안다 (ui/core/render 금지 — planner와 동일 위치).
// ui 계층은 이 배럴에서 import한다.

export {
  ApiClient,
  MemorySessionStore,
  SESSION_STORAGE_KEY,
  REQUEST_TIMEOUT_MS,
  LOCAL_RETRY_INTERVAL_MS,
  OFFLINE_POLL_INTERVAL_MS,
  MSG_NETWORK_KO,
  MSG_TIMEOUT_KO,
  MSG_LOCAL_MODE_KO,
  MSG_UNAUTHORIZED_KO,
  MSG_LOGIN_INVALID_KO,
  MSG_CONFLICT_KO,
  MSG_SERVER_ERROR_KO,
  nextConnectionState,
  connectionLabel,
  connectionLabelKo,
  parseStoredSession,
  pickMessageKo,
} from './client';
export type {
  ApiClientOptions,
  ApiResult,
  AuthSession,
  ConnectionEvent,
  ConnectionLabel,
  ConnectionState,
  FetchInit,
  FetchLike,
  HttpMethod,
  LoginResult,
  RequestOptions,
  ServerMode,
  SessionStore,
  TimerHost,
} from './client';

export {
  EntityClient,
  RunsClient,
  WorkcellApi,
  createWorkcellApi,
  buildListQuery,
  buildRunsQuery,
  extractConflictCurrent,
  extractLock,
  ENTITY_KINDS,
} from './resources';
export type {
  ApiFailure,
  EntityDocMap,
  EntityKind,
  GetResult,
  ListOptions,
  ListResult,
  LockAction,
  LockKind,
  LockResult,
  RemoveResult,
  RunCreateResult,
  RunGetResult,
  RunListOptions,
  RunListResult,
  SaveResult,
  TaskStatsResult,
} from './resources';

export {
  ApiCache,
  IndexedDbKVStorage,
  MemoryKVStorage,
  OfflineOutbox,
  API_CACHE_DB_NAME,
  API_CACHE_DB_VERSION,
  KV_STORES,
  MSG_OUTBOX_CORRUPT_KO,
  conflictKey,
  outboxKey,
  listCacheKey,
  lastSyncAgeKo,
  listThroughCache,
  getThroughCache,
  sendOutboxOp,
} from './offline';
export type {
  CachedList,
  CachedRecord,
  ConflictRecord,
  FlushReport,
  GetThroughCacheResult,
  KVStorage,
  ListThroughCacheResult,
  OutboxOp,
  OutboxOpKind,
  OutboxSendOutcome,
  StoreName,
} from './offline';
